In [2]:
import pandas as pd
pd.__version__


'1.2.4'

In [3]:
import numpy as np

In [4]:
pd.__version__

'1.2.4'

In [5]:
matrix = np.random.randint(1,10,(2,3))
matrix

array([[9, 4, 4],
       [8, 7, 7]])

In [8]:
matrix.T   # transpose 

array([[9, 8],
       [4, 7],
       [4, 7]])

In [6]:
matrix.ravel()

array([9, 4, 4, 8, 7, 7])

In [7]:
matrix.reshape(2,3)

array([[9, 4, 4],
       [8, 7, 7]])

In [ ]:
# resize vs. reshape

# reshize 에서 추가 요소는 0으로 채워진다



In [10]:
a = np.random.randint(1,10,(2,6))
a

array([[8, 2, 8, 8, 6, 5],
       [6, 6, 8, 5, 1, 4]])

In [11]:
a.resize(6,2)
a

array([[8, 2],
       [8, 8],
       [6, 5],
       [6, 6],
       [8, 5],
       [1, 4]])

In [16]:
b = np.random.randint(1,10,(2,6))
# 추가요소는 0으로 채워짐 
b.resize((2,10))
b

array([[3, 3, 3, 6, 5, 3, 3, 9, 9, 4],
       [8, 7, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
# 요소가 12개에서 9개로 줄어듬
c = np.random.randint(1,10,(2,6))
c.resize((3,3))
c

array([[1, 8, 4],
       [2, 1, 6],
       [7, 1, 3]])

In [ ]:
# append : 배열의 끝에 값 추가 value or 배열 추가 
# axis = 1 -> 열방향 추가
# axis = 0 -> 행방향 추가 


In [18]:
ap_a = np.arange(1,10).reshape(3,3)
print('a=', ap_a)
ap_b = np.arange(10,19).reshape(3,3)
print('b=', ap_b)

a= [[1 2 3]
 [4 5 6]
 [7 8 9]]
b= [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [20]:
# no axis defined
result1 = np.append(ap_a, ap_b)
print(result1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [22]:
# axis = 1   열방향 추가 
result2 = np.append(ap_a, ap_b, axis = 1)
print(result2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [25]:
# axis = 0  행방향 추가 
result3 = np.append(ap_a, ap_b, axis = 0)
print(result3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [26]:
# insert
ins_a = np.arange(1,10).reshape(3,3)
print(ins_a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
np.insert(ins_a, 4, 999)

array([  1,   2,   3,   4, 999,   5,   6,   7,   8,   9])

In [28]:
np.insert(ins_a, 1, 999, axis = 0)

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
np.insert(lins, )

In [29]:
# delete
del_a = np.arange(1,10).reshape(3,3)
print(del_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
np.delete(del_a,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.delete(del_a, 2, axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.delete(del_a, 1, axis = 1)

array([[1, 3],
       [4, 6],
       [7, 9]])